apiVersion: apps/v1
kind: Deployment
metadata:
  name: expiration-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: expiration
  template:
    metadata:
      labels:
        app: expiration
    spec:
      containers:
        - name: expiration
          # image: us.gcr.io/ticketing-dev-359710/expiration
          image: manelcastro/expiration
          env:
            - name: NATS_CLIENT_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name # Pods name (randomly generated)
            - name: NATS_URL
              value: "http://nats-srv:4222"
            - name: NATS_CLUSTER_ID
              value: ticketing
            - name: REDIS_HOST
              value: expiration-redis-srv
### NO NEED FOR CLUSTER IP ###
# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: expiration-srv
# spec:
#   selector:
#     app: expiration
#   type: ClusterIP
#   ports:
#     - name: expiration
#       protocol: TCP
#       port: 3000
#       targetPort: 3000
