apiVersion: skaffold/v2alpha3
kind: Config
deploy:
  kubectl:
    manifests:
      - ./infra/k8s/*
      - ./infra/k8s-dev/*
build:
  local:
    push: false
  # googleCloudBuild:
  #   projectId: ticketing-dev-359710
  artifacts:
    - image: manelcastro/auth
      # - image: us.gcr.io/ticketing-dev-359710/auth
      context: auth
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "src/**/*.ts"
            dest: .
    - image: manelcastro/client
      # - image: us.gcr.io/ticketing-dev-359710/client
      context: client
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "src/**/*.js"
            dest: .
    - image: manelcastro/tickets
      # - image: us.gcr.io/ticketing-dev-359710/tickets
      context: tickets
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "src/**/*.ts"
            dest: .
    - image: manelcastro/orders
      # - image: us.gcr.io/ticketing-dev-359710/orders
      context: orders
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "src/**/*.ts"
            dest: .
    - image: manelcastro/expiration
      # - image: us.gcr.io/ticketing-dev-359710/expiration
      context: expiration
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "src/**/*.ts"
            dest: .
    - image: manelcastro/payments
      # - image: us.gcr.io/ticketing-dev-359710/payments
      context: payments
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "src/**/*.ts"
            dest: .
