name: deploy-auth

on: 
  push: #if merge actually counts as push  
    branches: 
      - master 
    paths:
      - 'ticketing/auth/**'
  
jobs:
  build: 
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v2 #checkout all the code inside repo 
      - run: cd ticketing/auth && docker build -t manelcastro/auth
